apiVersion: apps/v1   # K8s is extensible. We can add our own custom objects. Preset list of different objects that we want our K8s to look at
kind: Deployment         # type of object that we want to create from that preset pool of objects
metadata:         # config options for the object we are about to create
  name: posts-depl     # when the pod is created , give it the name of posts.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: stephengrider/posts:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
